#pragma once

#ifdef AUDIO_ENABLE
#    define STARTUP_SONG SONG(PLANCK_SOUND)
#endif

#define NO_DEBUG
#define USER_PRINT
#define NO_ACTION_ONESHOT

#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD

#define CAPS_WORD_IDLE_TIMEOUT 0
