#pragma once

#ifdef AUDIO_ENABLE
#    define STARTUP_SONG SONG(PLANCK_SOUND)
#endif

#define NO_DEBUG
#define NO_PRINT
#define NO_ACTION_ONESHOT

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 7
#define MOUSEKEY_MAX_SPEED 12
#define MOUSEKEY_TIME_TO_MAX 36
#define MOUSEKEY_FRICTION 70

#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
