#pragma once

#define NO_DEBUG
#define USER_PRINT
#define NO_ACTION_ONESHOT

#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY

#define CAPS_WORD_IDLE_TIMEOUT 1000

#define MOUSEKEY_INERTIA
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 7
#define MOUSEKEY_MAX_SPEED 12
#define MOUSEKEY_TIME_TO_MAX 36
#define MOUSEKEY_FRICTION 70
